[[Kaleido]]
arch = "aarch64"
git-tree-sha1 = "dd979a3fc47606530525152f643f40ae913ab026"
os = "macos"

    [[Kaleido.download]]
    sha256 = "0fdbb1a8e1c53b31218a315a31d05cb16dbdfc9931a589d829bb77f51a250e20"
    url = "https://github.com/JuliaBinaryWrappers/Kaleido_jll.jl/releases/download/Kaleido-v0.2.1+0/Kaleido.v0.2.1.aarch64-apple-darwin.tar.gz"
[[Kaleido]]
arch = "aarch64"
git-tree-sha1 = "d8a9f9d9ba69e1ee2845c64ab25cea331f56f3c6"
libc = "glibc"
os = "linux"

    [[Kaleido.download]]
    sha256 = "a564d7af721c6a4fee5b302cc34524487859d6fc1bfd1a7c723f72cfde2c9219"
    url = "https://github.com/JuliaBinaryWrappers/Kaleido_jll.jl/releases/download/Kaleido-v0.2.1+0/Kaleido.v0.2.1.aarch64-linux-gnu.tar.gz"
[[Kaleido]]
arch = "i686"
git-tree-sha1 = "531db621cd49a9be2be0cd068d786273c73e4fcc"
os = "windows"

    [[Kaleido.download]]
    sha256 = "08dbc113e706be0fd893e37cff74f8b193b31703528fa920332dbe6320aa74d4"
    url = "https://github.com/JuliaBinaryWrappers/Kaleido_jll.jl/releases/download/Kaleido-v0.2.1+0/Kaleido.v0.2.1.i686-w64-mingw32.tar.gz"
[[Kaleido]]
arch = "x86_64"
git-tree-sha1 = "6fd6b73cd862be1bd96f6fe34610497b25e462db"
os = "macos"

    [[Kaleido.download]]
    sha256 = "ee8d8674da780d0c6c56eb984074545c33e50c210cd3de0f6d2020ccf0361f98"
    url = "https://github.com/JuliaBinaryWrappers/Kaleido_jll.jl/releases/download/Kaleido-v0.2.1+0/Kaleido.v0.2.1.x86_64-apple-darwin.tar.gz"
[[Kaleido]]
arch = "x86_64"
git-tree-sha1 = "bd3689c641088ffac77cbb10f229cae0537d286a"
libc = "glibc"
os = "linux"

    [[Kaleido.download]]
    sha256 = "5b8211ff7d041999bb6a94116d8d26b545056c69a4aa49cd900d0317ae4fd2ea"
    url = "https://github.com/JuliaBinaryWrappers/Kaleido_jll.jl/releases/download/Kaleido-v0.2.1+0/Kaleido.v0.2.1.x86_64-linux-gnu.tar.gz"
[[Kaleido]]
arch = "x86_64"
git-tree-sha1 = "7914a56da888d6a06d00c87f97e873c60e97acc7"
os = "windows"

    [[Kaleido.download]]
    sha256 = "5251d44dd5495404a8ad7d9f6120b0ce65819111c518c767ee46f0c7b1424918"
    url = "https://github.com/JuliaBinaryWrappers/Kaleido_jll.jl/releases/download/Kaleido-v0.2.1+0/Kaleido.v0.2.1.x86_64-w64-mingw32.tar.gz"
